# Generated by Django 4.1.5 on 2023-02-12 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiIdiom',
            fields=[
                ('idiom', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='KanjiSingle',
            fields=[
                ('kanji', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KanjiTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaimyon.kanjisingle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaimyon.tag')),
            ],
        ),
        migrations.CreateModel(
            name='IdiomTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaimyon.kanjiidiom')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaimyon.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='kanjitagrelation',
            constraint=models.UniqueConstraint(fields=('kanji', 'tag'), name='unique_kanji_tag'),
        ),
        migrations.AddConstraint(
            model_name='idiomtagrelation',
            constraint=models.UniqueConstraint(fields=('idiom', 'tag'), name='unique_idiom_tag'),
        ),
    ]
