# Generated by Django 4.1.5 on 2023-02-12 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaimyon', '0002_remove_kanjitagrelation_kanji_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanjiTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaimyon.kanjisingle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaimyon.tag')),
            ],
        ),
        migrations.CreateModel(
            name='IdiomTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaimyon.kanjiidiom')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaimyon.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='kanjitagrelation',
            constraint=models.UniqueConstraint(fields=('kanji', 'tag'), name='unique_kanji_tag'),
        ),
    ]
