# Generated by Django 4.1.5 on 2023-02-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaimyon', '0003_kanjitagrelation_idiomtagrelation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='idiomtagrelation',
            constraint=models.UniqueConstraint(fields=('idiom', 'tag'), name='unique_idiom_tag'),
        ),
    ]
